version: "2"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./php:/var/www/html/
        links:
            - mariadb
        networks:
            - default
    mariadb:
        image: mariadb:10.4.5
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: kigaDB
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./Database:/docker-entrypoint-initdb.d
            - ./persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:
